GO
CREATE DATABASE VendasDB;
GO
USE VendasDB;

GO
CREATE TABLE "NOTA_FISCAL"
(
  "CODNOTA"  INTEGER NOT NULL,
  "CODVENDA"  INTEGER,  
  "DESTINATARIOREMETENTE"  VARCHAR(100),  
  "DTEMISSAO"  DATE,
  "DTSAIDAENTRADA"  DATE,    
  "NUMNOTA"  INTEGER,  
  "VALORTOTALPRODUTOS"  DOUBLE PRECISION,
  "VALORTOTALNOTA"  DOUBLE PRECISION,    
  "TRANSFRETE"  INTEGER,        
  "NUMERORECIBO"  VARCHAR(50),  
 PRIMARY KEY ("CODNOTA")
);

CREATE TABLE "NOTAFISCALITENS"
(
  "CODITEM"  INTEGER NOT NULL,
  "CODNOTA"  INTEGER,
  "CODPRO"  INTEGER,
  "DESCRPRO"  VARCHAR(80),
  "UNIDADE"  VARCHAR(3),
  "QTDE"  DOUBLE PRECISION,
  "VALORTOTAL"  DOUBLE PRECISION,  
  "CODIGOPRODUTOEXTERNO"  VARCHAR(20),
  "VALORUNITARIO"  DOUBLE PRECISION,    
 PRIMARY KEY ("CODITEM")
);
ALTER TABLE "NOTAFISCALITENS" ADD CONSTRAINT "FK_NOTAFISCALITENS_NOTAFISCAL" FOREIGN KEY ("CODNOTA") REFERENCES "NOTA_FISCAL" ("CODNOTA") ON DELETE CASCADE;

GO
BEGIN TRY
	BEGIN TRANSACTION
		INSERT [dbo].[NOTA_FISCAL] ([CODNOTA], [CODVENDA], [DESTINATARIOREMETENTE], [DTEMISSAO], [DTSAIDAENTRADA], [NUMNOTA], [VALORTOTALPRODUTOS], [VALORTOTALNOTA], [TRANSFRETE], [NUMERORECIBO]) VALUES (1, 82536089, N'Luís Sebastião Martin Galvão', CAST(N'2020-10-01' AS Date), CAST(N'2020-10-01' AS Date), NULL, NULL, NULL, NULL, NULL)
		INSERT [dbo].[NOTA_FISCAL] ([CODNOTA], [CODVENDA], [DESTINATARIOREMETENTE], [DTEMISSAO], [DTSAIDAENTRADA], [NUMNOTA], [VALORTOTALPRODUTOS], [VALORTOTALNOTA], [TRANSFRETE], [NUMERORECIBO]) VALUES (2, 34825200, N'Sarah Gabriela Renata Peixoto', CAST(N'2020-10-01' AS Date), CAST(N'2020-10-10' AS Date), NULL, NULL, NULL, NULL, NULL)
		INSERT [dbo].[NOTA_FISCAL] ([CODNOTA], [CODVENDA], [DESTINATARIOREMETENTE], [DTEMISSAO], [DTSAIDAENTRADA], [NUMNOTA], [VALORTOTALPRODUTOS], [VALORTOTALNOTA], [TRANSFRETE], [NUMERORECIBO]) VALUES (3, 2099537, N'Andreia Rita da Rocha', CAST(N'2020-10-05' AS Date), CAST(N'2020-10-24' AS Date), NULL, NULL, NULL, NULL, NULL)
		INSERT [dbo].[NOTA_FISCAL] ([CODNOTA], [CODVENDA], [DESTINATARIOREMETENTE], [DTEMISSAO], [DTSAIDAENTRADA], [NUMNOTA], [VALORTOTALPRODUTOS], [VALORTOTALNOTA], [TRANSFRETE], [NUMERORECIBO]) VALUES (4, 7211656, N'Oliver Ricardo Pereira', CAST(N'2020-12-05' AS Date), CAST(N'2020-12-18' AS Date), NULL, NULL, NULL, NULL, NULL)
		INSERT [dbo].[NOTA_FISCAL] ([CODNOTA], [CODVENDA], [DESTINATARIOREMETENTE], [DTEMISSAO], [DTSAIDAENTRADA], [NUMNOTA], [VALORTOTALPRODUTOS], [VALORTOTALNOTA], [TRANSFRETE], [NUMERORECIBO]) VALUES (5, 81357684, N'Kamilly Alícia dos Santos', CAST(N'2020-12-12' AS Date), CAST(N'2021-01-15' AS Date), NULL, NULL, NULL, NULL, N'')
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (1, 1, 3552, N'', N'1', 270, 442338, N'270', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (2, 2, 4552, N'', N'3', 300, 322164, N'100', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (3, 3, 2231, N'', N'1', 550, 560063, N'550', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (4, 3, 4552, N'', N'1', 100, 322164, N'100', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (5, 4, NULL, N'', N'', NULL, NULL, N'', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (6, 4, NULL, N'', N'', NULL, NULL, N'', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (7, 5, NULL, N'', N'', NULL, NULL, N'', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (8, 5, NULL, N'', N'', NULL, NULL, N'', NULL)
		INSERT [dbo].[NOTAFISCALITENS] ([CODITEM], [CODNOTA], [CODPRO], [DESCRPRO], [UNIDADE], [QTDE], [VALORTOTAL], [CODIGOPRODUTOEXTERNO], [VALORUNITARIO]) VALUES (9, 5, NULL, N'', N'', NULL, NULL, N'', NULL)

	COMMIT TRANSACTION
	RETURN
END TRY

BEGIN CATCH
	ROLLBACK
	SELECT ERROR_MESSAGE() 		
	RETURN
END CATCH

GO
SELECT nf.CODNOTA, SUM(nfi.VALORTOTAL) AS [Valor Total], SUM(nfi.QTDE) AS [Quantidade] 
FROM dbo.NOTA_FISCAL AS nf INNER JOIN dbo.NOTAFISCALITENS AS nfi ON nf.CODNOTA = nfi.CODNOTA WHERE MONTH(nf.DTEMISSAO) = '12' GROUP BY nf.CODNOTA;

GO  
CREATE PROCEDURE Sp_GetNotaFiscalByEmission
    @DataEmissao DATE   
AS   
	SELECT * FROM dbo.NOTA_FISCAL AS nf WHERE nf.DTEMISSAO = @DataEmissao;

GO 
EXEC Sp_GetNotaFiscalByEmission '2020-12-12'
Go